apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kcp-exporter
  namespace: kcp
  labels:
    app: kcp-exporter
spec:
  selector:
    matchLabels:
      app: kcp-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - kcp
