#!/usr/bin/env bash
# Creates sample KCP resources for demo/testing.
# Requires: KCP admin kubeconfig generated by setup.sh
# Does NOT require the kcp kubectl plugin — uses --server flag for workspace switching.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export KUBECONFIG="${SCRIPT_DIR}/kcp-admin.kubeconfig"

KCP_BASE="https://kcp.localhost:8443"

info()  { echo "===> $*"; }
error() { echo "ERROR: $*" >&2; exit 1; }

# kubectl wrapper that targets a specific workspace
kws() {
  local ws_path="$1"; shift
  kubectl --server="${KCP_BASE}/clusters/${ws_path}" "$@"
}

if [ ! -f "${KUBECONFIG}" ]; then
  error "KCP admin kubeconfig not found at ${KUBECONFIG}. Run setup.sh first."
fi

# Test connectivity
info "Testing KCP connectivity..."
kws root api-resources --request-timeout=10s >/dev/null 2>&1 || \
  error "Cannot connect to KCP. Is the cluster running?"

# -------------------------------------------------------------------
# Create workspaces
# -------------------------------------------------------------------
info "Creating workspaces..."

for ws in org-alpha org-beta org-gamma; do
  if kws root get workspace "${ws}" >/dev/null 2>&1; then
    info "Workspace '${ws}' already exists, skipping."
  else
    kws root apply -f - <<EOF
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: ${ws}
spec:
  type:
    name: universal
    path: root
EOF
  fi
done

# Wait for workspaces to be ready
info "Waiting for workspaces to become Ready..."
for ws in org-alpha org-beta org-gamma; do
  for attempt in $(seq 1 12); do
    phase=$(kws root get workspace "${ws}" -o jsonpath='{.status.phase}' 2>/dev/null || echo "Unknown")
    if [ "${phase}" = "Ready" ]; then
      info "Workspace '${ws}' is Ready."
      break
    fi
    if [ "${attempt}" -eq 12 ]; then
      info "Warning: workspace '${ws}' still in phase '${phase}' after 60s"
    fi
    sleep 5
  done
done

# -------------------------------------------------------------------
# Create APIResourceSchema + APIExport in org-alpha
# -------------------------------------------------------------------
info "Creating APIResourceSchema and APIExport in org-alpha..."

kws root:org-alpha apply -f - <<'EOF'
apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v1.widgets.example.com
spec:
  group: example.com
  names:
    kind: Widget
    listKind: WidgetList
    plural: widgets
    singular: widget
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        description: A Widget is a demo resource
        type: object
        properties:
          spec:
            type: object
            properties:
              color:
                type: string
              size:
                type: string
                enum: ["small", "medium", "large"]
          status:
            type: object
            properties:
              phase:
                type: string
      subresources:
        status: {}
EOF

kws root:org-alpha apply -f - <<'EOF'
apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: widgets
spec:
  latestResourceSchemas:
    - v1.widgets.example.com
EOF

info "Waiting for APIExport to be ready..."
sleep 5

# -------------------------------------------------------------------
# Create APIBindings in consumer workspaces
# -------------------------------------------------------------------
for ws in org-beta org-gamma; do
  info "Creating APIBinding in ${ws}..."
  kws "root:${ws}" apply -f - <<EOF
apiVersion: apis.kcp.io/v1alpha1
kind: APIBinding
metadata:
  name: widgets
spec:
  reference:
    export:
      path: root:org-alpha
      name: widgets
EOF
done

# Wait for bindings to be ready
info "Waiting for APIBindings to become Bound..."
sleep 10

for ws in org-beta org-gamma; do
  phase=$(kws "root:${ws}" get apibinding widgets -o jsonpath='{.status.phase}' 2>/dev/null || echo "Unknown")
  info "APIBinding 'widgets' in ${ws}: ${phase}"
done

# -------------------------------------------------------------------
# Create sample Widget resources
# -------------------------------------------------------------------
COLORS=("red" "blue" "green" "yellow" "purple")
SIZES=("small" "medium" "large")

for ws in org-beta org-gamma; do
  info "Creating sample Widgets in ${ws}..."

  # Ensure default namespace exists
  kws "root:${ws}" create namespace default --dry-run=client -o yaml 2>/dev/null | \
    kws "root:${ws}" apply -f - 2>/dev/null || true

  for i in 1 2 3; do
    color=${COLORS[$((RANDOM % ${#COLORS[@]}))]}
    size=${SIZES[$((RANDOM % ${#SIZES[@]}))]}
    kws "root:${ws}" apply -f - <<EOF
apiVersion: example.com/v1
kind: Widget
metadata:
  name: widget-${i}
  namespace: default
spec:
  color: ${color}
  size: ${size}
EOF
  done
done

# -------------------------------------------------------------------
# Summary
# -------------------------------------------------------------------
echo ""
echo "=============================================="
echo "  Demo resources created!"
echo "=============================================="
echo ""
echo "  Workspaces:  org-alpha, org-beta, org-gamma"
echo "  APIExport:   widgets (in org-alpha)"
echo "  APIBindings: widgets (in org-beta, org-gamma)"
echo "  Widgets:     3 per consumer workspace"
echo ""
echo "  Explore:"
echo "    kubectl --server=${KCP_BASE}/clusters/root get workspaces"
echo "    kubectl --server=${KCP_BASE}/clusters/root:org-alpha get apiexports"
echo "    kubectl --server=${KCP_BASE}/clusters/root:org-beta get widgets"
echo ""
echo "  Check Grafana 'KCP Resources' dashboard:"
echo "    http://localhost:3000"
echo "=============================================="
