#!/usr/bin/env bash
# Creates sample KCP resources for demo/testing.
# Requires: KCP admin kubeconfig generated by setup.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export KUBECONFIG="${SCRIPT_DIR}/kcp-admin.kubeconfig"

info()  { echo "===> $*"; }
error() { echo "ERROR: $*" >&2; exit 1; }

if [ ! -f "${KUBECONFIG}" ]; then
  error "KCP admin kubeconfig not found at ${KUBECONFIG}. Run setup.sh first."
fi

# Test connectivity
info "Testing KCP connectivity..."
kubectl api-resources --request-timeout=10s >/dev/null 2>&1 || \
  error "Cannot connect to KCP. Is the cluster running?"

# -------------------------------------------------------------------
# Create workspaces
# -------------------------------------------------------------------
info "Creating workspaces..."

for ws in org-alpha org-beta org-gamma; do
  if kubectl get workspace "${ws}" >/dev/null 2>&1; then
    info "Workspace '${ws}' already exists, skipping."
  else
    kubectl create workspace "${ws}" --type universal || \
      kubectl apply -f - <<EOF
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: ${ws}
spec:
  type:
    name: universal
    path: root
EOF
  fi
done

# Wait for workspaces to be ready
info "Waiting for workspaces to become Ready..."
for ws in org-alpha org-beta org-gamma; do
  kubectl wait --for=jsonpath='{.status.phase}'=Ready workspace/${ws} --timeout=60s || \
    info "Warning: workspace ${ws} may not be ready yet"
done

# -------------------------------------------------------------------
# Create APIResourceSchema + APIExport in org-alpha
# -------------------------------------------------------------------
info "Creating APIResourceSchema and APIExport in org-alpha..."
kubectl ws use org-alpha 2>/dev/null || kubectl ws root:org-alpha 2>/dev/null || true

kubectl apply -f - <<'EOF'
apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v1.widgets.example.com
spec:
  group: example.com
  names:
    kind: Widget
    listKind: WidgetList
    plural: widgets
    singular: widget
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        description: A Widget is a demo resource
        type: object
        properties:
          spec:
            type: object
            properties:
              color:
                type: string
              size:
                type: string
                enum: ["small", "medium", "large"]
          status:
            type: object
            properties:
              phase:
                type: string
      subresources:
        status: {}
EOF

kubectl apply -f - <<'EOF'
apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: widgets
spec:
  latestResourceSchemas:
    - v1.widgets.example.com
EOF

info "Waiting for APIExport to be ready..."
sleep 5

# -------------------------------------------------------------------
# Create APIBindings in consumer workspaces
# -------------------------------------------------------------------
EXPORT_PATH="root:org-alpha"

for ws in org-beta org-gamma; do
  info "Creating APIBinding in ${ws}..."
  kubectl ws use "${ws}" 2>/dev/null || kubectl ws "root:${ws}" 2>/dev/null || true

  kubectl apply -f - <<EOF
apiVersion: apis.kcp.io/v1alpha1
kind: APIBinding
metadata:
  name: widgets
spec:
  reference:
    export:
      path: ${EXPORT_PATH}
      name: widgets
EOF
done

# Wait for bindings to be ready
info "Waiting for APIBindings to become Bound..."
sleep 10

# -------------------------------------------------------------------
# Create sample Widget resources
# -------------------------------------------------------------------
COLORS=("red" "blue" "green" "yellow" "purple")
SIZES=("small" "medium" "large")

for ws in org-beta org-gamma; do
  info "Creating sample Widgets in ${ws}..."
  kubectl ws use "${ws}" 2>/dev/null || kubectl ws "root:${ws}" 2>/dev/null || true

  for i in 1 2 3; do
    color=${COLORS[$((RANDOM % ${#COLORS[@]}))]}
    size=${SIZES[$((RANDOM % ${#SIZES[@]}))]}
    kubectl apply -f - <<EOF
apiVersion: example.com/v1
kind: Widget
metadata:
  name: widget-${i}
  namespace: default
spec:
  color: ${color}
  size: ${size}
EOF
  done
done

# -------------------------------------------------------------------
# Summary
# -------------------------------------------------------------------
info "Switching back to root workspace..."
kubectl ws use root 2>/dev/null || kubectl ws root 2>/dev/null || true

echo ""
echo "=============================================="
echo "  Demo resources created!"
echo "=============================================="
echo ""
echo "  Workspaces:  org-alpha, org-beta, org-gamma"
echo "  APIExport:   widgets (in org-alpha)"
echo "  APIBindings: widgets (in org-beta, org-gamma)"
echo "  Widgets:     3 per consumer workspace"
echo ""
echo "  Explore:"
echo "    kubectl get workspaces"
echo "    kubectl ws org-alpha && kubectl get apiexports"
echo "    kubectl ws org-beta && kubectl get widgets"
echo ""
echo "  Check Grafana 'KCP Resources' dashboard:"
echo "    http://localhost:3000"
echo "=============================================="
