#!/usr/bin/env bash
# Creates sample KCP resources for demo/testing.
# Requires: KCP admin kubeconfig generated by setup.sh
# Does NOT require the kcp kubectl plugin — uses --server flag for workspace switching.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export KUBECONFIG="${SCRIPT_DIR}/kcp-admin.kubeconfig"

KCP_BASE="https://kcp.localhost:8443"

info()  { echo "===> $*"; }
error() { echo "ERROR: $*" >&2; exit 1; }

# kubectl wrapper that targets a specific workspace
kws() {
  local ws_path="$1"; shift
  kubectl --server="${KCP_BASE}/clusters/${ws_path}" "$@"
}

# Poll until condition is met or timeout
wait_for() {
  local desc="$1" timeout="$2" interval="$3"; shift 3
  local deadline=$((SECONDS + timeout))
  while [ $SECONDS -lt $deadline ]; do
    if "$@" 2>/dev/null; then return 0; fi
    sleep "$interval"
  done
  error "Timed out waiting for: ${desc} (${timeout}s)"
}

if [ ! -f "${KUBECONFIG}" ]; then
  error "KCP admin kubeconfig not found at ${KUBECONFIG}. Run setup.sh first."
fi

# Test connectivity
info "Testing KCP connectivity..."
kws root api-resources --request-timeout=10s >/dev/null 2>&1 || \
  error "Cannot connect to KCP. Is the cluster running?"

# -------------------------------------------------------------------
# Create workspaces
# -------------------------------------------------------------------
info "Creating workspaces..."

for ws in org-alpha org-beta org-gamma; do
  if kws root get workspace "${ws}" >/dev/null 2>&1; then
    info "Workspace '${ws}' already exists, skipping."
  else
    kws root apply -f - <<EOF
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: ${ws}
spec:
  type:
    name: organization
    path: root
EOF
  fi
done

# Wait for workspaces to be ready
info "Waiting for workspaces to become Ready..."
for ws in org-alpha org-beta org-gamma; do
  for attempt in $(seq 1 12); do
    phase=$(kws root get workspace "${ws}" -o jsonpath='{.status.phase}' 2>/dev/null || echo "Unknown")
    if [ "${phase}" = "Ready" ]; then
      info "Workspace '${ws}' is Ready."
      break
    fi
    if [ "${attempt}" -eq 12 ]; then
      info "Warning: workspace '${ws}' still in phase '${phase}' after 60s"
    fi
    sleep 5
  done
done

# -------------------------------------------------------------------
# Create APIResourceSchema + APIExport in root workspace
# -------------------------------------------------------------------
# NOTE: The APIExport is created in the root workspace because KCP's
# Deep SubjectAccessReview for bind permissions only evaluates RBAC
# correctly in the root workspace (bootstrap policy). This matches
# how KCP's built-in exports (tenancy.kcp.io, topology.kcp.io) work.
info "Creating APIResourceSchema and APIExport in root workspace..."

kws root apply -f - <<'EOF'
apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v1.widgets.example.com
spec:
  group: example.com
  names:
    kind: Widget
    listKind: WidgetList
    plural: widgets
    singular: widget
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        description: A Widget is a demo resource
        type: object
        properties:
          spec:
            type: object
            properties:
              color:
                type: string
              size:
                type: string
                enum: ["small", "medium", "large"]
          status:
            type: object
            properties:
              phase:
                type: string
      subresources:
        status: {}
EOF

kws root apply -f - <<'EOF'
apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: widgets
spec:
  latestResourceSchemas:
    - v1.widgets.example.com
  maximalPermissionPolicy:
    local: {}
EOF

# Grant bind permission on the widgets APIExport to all authenticated users.
kws root apply -f - <<'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: widgets-bind
rules:
  - apiGroups: ["apis.kcp.io"]
    resources: ["apiexports"]
    resourceNames: ["widgets"]
    verbs: ["bind"]
EOF
kws root apply -f - <<'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: widgets-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: widgets-bind
subjects:
  - kind: Group
    name: "system:authenticated"
    apiGroup: rbac.authorization.k8s.io
EOF

# Grant maximal permission policy RBAC — required when maximalPermissionPolicy.local is set.
kws root apply -f - <<'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: widgets-maximal-permission-policy
rules:
  - apiGroups: ["example.com"]
    resources: ["widgets"]
    verbs: ["*"]
  - apiGroups: ["example.com"]
    resources: ["widgets/status"]
    verbs: ["get", "list", "watch"]
EOF
kws root apply -f - <<'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: widgets-maximal-permission-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: widgets-maximal-permission-policy
subjects:
  - kind: Group
    name: "apis.kcp.io:binding:system:authenticated"
    apiGroup: rbac.authorization.k8s.io
EOF

info "Waiting for APIExport to be discoverable..."
wait_for "APIExport 'widgets' exists in root" 30 3 \
  kws root get apiexport widgets -o name

# -------------------------------------------------------------------
# Grant admin access in child workspaces
# -------------------------------------------------------------------
# KCP's admin battery may be disabled in the Helm chart, so system:kcp:admin
# may not have automatic access in child workspaces. Grant it explicitly so
# both demo.sh and the kcp-exporter (same cert) can query child workspace APIs.
info "Granting admin access in child workspaces..."
for ws in org-alpha org-beta org-gamma; do
  kws "root:${ws}" apply -f - <<'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp-admin-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: Group
    name: system:kcp:admin
    apiGroup: rbac.authorization.k8s.io
EOF
done

# -------------------------------------------------------------------
# Create APIBindings in consumer workspaces
# -------------------------------------------------------------------
for ws in org-alpha org-beta org-gamma; do
  info "Creating APIBinding in ${ws}..."
  for attempt in $(seq 1 4); do
    if kws "root:${ws}" apply -f - <<EOF 2>/dev/null
apiVersion: apis.kcp.io/v1alpha1
kind: APIBinding
metadata:
  name: widgets
spec:
  reference:
    export:
      path: root
      name: widgets
EOF
    then
      info "APIBinding created in ${ws}."
      break
    fi
    if [ "${attempt}" -eq 4 ]; then
      info "Warning: APIBinding in ${ws} failed after ${attempt} attempts."
    else
      info "Retrying APIBinding in ${ws} (attempt ${attempt}/4)..."
      sleep 10
    fi
  done
done

# Wait for bindings to be ready (polling instead of fixed sleep)
info "Waiting for APIBindings to become Bound..."
for ws in org-alpha org-beta org-gamma; do
  info "Waiting for APIBinding in ${ws} to become Bound..."
  wait_for "APIBinding widgets in ${ws} Bound" 60 5 \
    bash -c "phase=\$(kubectl --server=${KCP_BASE}/clusters/root:${ws} get apibinding widgets -o jsonpath='{.status.phase}' 2>/dev/null) && [ \"\$phase\" = 'Bound' ]"
  phase=$(kws "root:${ws}" get apibinding widgets -o jsonpath='{.status.phase}' 2>/dev/null || echo "Unknown")
  info "APIBinding 'widgets' in ${ws}: ${phase}"
done

# -------------------------------------------------------------------
# Create sample Widget resources
# -------------------------------------------------------------------
COLORS=("red" "blue" "green" "yellow" "purple")
SIZES=("small" "medium" "large")

for ws in org-alpha org-beta org-gamma; do
  info "Creating sample Widgets in ${ws}..."

  # Ensure default namespace exists
  kws "root:${ws}" create namespace default --dry-run=client -o yaml 2>/dev/null | \
    kws "root:${ws}" apply -f - 2>/dev/null || true

  for i in 1 2 3; do
    color=${COLORS[$((RANDOM % ${#COLORS[@]}))]}
    size=${SIZES[$((RANDOM % ${#SIZES[@]}))]}
    kws "root:${ws}" apply -f - <<EOF
apiVersion: example.com/v1
kind: Widget
metadata:
  name: widget-${i}
  namespace: default
spec:
  color: ${color}
  size: ${size}
EOF
  done
done

# -------------------------------------------------------------------
# Verification
# -------------------------------------------------------------------
info "Running verification checks..."
PASS=true

# Check workspaces
ws_count=$(kws root get workspaces -o json | python3 -c "import sys,json; print(len(json.load(sys.stdin)['items']))")
[ "$ws_count" -ge 3 ] && info "PASS: ${ws_count} workspaces found" || { info "FAIL: only ${ws_count} workspaces"; PASS=false; }

# Check APIExport
kws root get apiexport widgets -o name >/dev/null 2>&1 && info "PASS: APIExport exists" || { info "FAIL: APIExport missing"; PASS=false; }

# Check APIBindings are Bound
for ws in org-alpha org-beta org-gamma; do
  phase=$(kws "root:${ws}" get apibinding widgets -o jsonpath='{.status.phase}' 2>/dev/null || echo "Missing")
  [ "$phase" = "Bound" ] && info "PASS: ${ws} binding is Bound" || { info "FAIL: ${ws} binding is ${phase}"; PASS=false; }
done

# Check Widgets exist
for ws in org-alpha org-beta org-gamma; do
  wc=$(kws "root:${ws}" get widgets -o json 2>/dev/null | python3 -c "import sys,json; print(len(json.load(sys.stdin).get('items',[])))" 2>/dev/null || echo "0")
  [ "$wc" -ge 1 ] && info "PASS: ${ws} has ${wc} widgets" || { info "FAIL: ${ws} has no widgets"; PASS=false; }
done

$PASS && info "All verification checks passed!" || error "Some verification checks failed — see above"

# -------------------------------------------------------------------
# Summary
# -------------------------------------------------------------------
echo ""
echo "=============================================="
echo "  Demo resources created!"
echo "=============================================="
echo ""
echo "  Workspaces:  org-alpha, org-beta, org-gamma"
echo "  APIExport:   widgets (in root)"
echo "  APIBindings: widgets (in org-alpha, org-beta, org-gamma)"
echo "  Widgets:     3 per workspace"
echo ""
echo "  Explore:"
echo "    kubectl --server=${KCP_BASE}/clusters/root get workspaces"
echo "    kubectl --server=${KCP_BASE}/clusters/root get apiexports"
echo "    kubectl --server=${KCP_BASE}/clusters/root:org-alpha get widgets"
echo "    kubectl --server=${KCP_BASE}/clusters/root:org-beta get widgets"
echo ""
echo "  Check Grafana 'KCP Resources' dashboard:"
echo "    http://localhost:3000"
echo "=============================================="
